// Generated by CoffeeScript 1.6.2
(function() {
  var BaseTransport;

  BaseTransport = (function() {
    /*
    */
    function BaseTransport(field) {
      this.field = field;
    }

    /*
    */


    BaseTransport.prototype.request = function(options, next) {
      return next();
    };

    /*
    */


    BaseTransport.prototype.watching = function(options, next) {
      return next();
    };

    return BaseTransport;

  })();

  module.exports = BaseTransport;

}).call(this);
