// Generated by CoffeeScript 1.6.2
(function() {
  var factories;

  factories = require("factories");

  module.exports = factories.any([require("./transport"), require("./inherit"), require("./none")]);

}).call(this);
