// Generated by CoffeeScript 1.6.2
(function() {
  var AnyFactory;

  AnyFactory = require("../../../../factory/any");

  module.exports = new AnyFactory([require("./transport"), require("./inherit"), require("./none")]);

}).call(this);
