// Generated by CoffeeScript 1.6.2
/*

happens when a field doesn't have a request option, but the 
parent might.
*/


(function() {
  var InheritTransport, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InheritTransport = (function(_super) {
    __extends(InheritTransport, _super);

    function InheritTransport() {
      _ref = InheritTransport.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    InheritTransport.prototype.request = function(options, next) {
      return this.field.parent._transporter.request(options, next);
    };

    /*
    */


    InheritTransport.prototype.watching = function(options) {
      if (options.model.get(options.property) != null) {
        return;
      }
      return this.request(options);
    };

    /*
    */


    InheritTransport.test = function(field) {
      return field.parent;
    };

    return InheritTransport;

  })(require("./base"));

  module.exports = InheritTransport;

}).call(this);
