// Generated by CoffeeScript 1.6.2
(function() {
  var NoTransport,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NoTransport = (function(_super) {
    __extends(NoTransport, _super);

    /*
    */


    function NoTransport() {}

    NoTransport.test = function() {
      return true;
    };

    return NoTransport;

  })(require("./base"));

  module.exports = NoTransport;

}).call(this);
