// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultMapper, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  DefaultMapper = (function(_super) {
    __extends(DefaultMapper, _super);

    /*
    */


    function DefaultMapper(field) {
      DefaultMapper.__super__.constructor.call(this, field);
      this._default = this._createDefault(field.options["default"]);
    }

    /*
    */


    DefaultMapper.prototype.map = function(model, data) {
      return data != null ? data : this._default.call(model);
    };

    /*
    */


    DefaultMapper.prototype._createDefault = function(def) {
      if (type(def) === "function") {
        return def;
      } else {
        return function() {
          return def;
        };
      }
    };

    /*
    */


    DefaultMapper.test = function(field) {
      return field.options["default"] != null;
    };

    return DefaultMapper;

  })(require("./base"));

  module.exports = DefaultMapper;

}).call(this);
