// Generated by CoffeeScript 1.6.2
(function() {
  var AnyFactory, mapperFactory;

  AnyFactory = require("../../../factory/any");

  mapperFactory = new AnyFactory([require("./root"), require("./default"), require("./none")]);

  module.exports = function(field) {
    var mapper;

    return mapper = mapperFactory.create(field);
  };

}).call(this);
