// Generated by CoffeeScript 1.6.2
(function() {
  var RootMapper,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RootMapper = (function(_super) {
    __extends(RootMapper, _super);

    /*
    */


    function RootMapper(field) {
      RootMapper.__super__.constructor.call(this, field);
    }

    /*
    */


    RootMapper.prototype.map = function(model, data) {
      return this._mapFields(this.field, model, {});
    };

    /*
    */


    RootMapper.prototype._mapFields = function(field, model, newData) {
      var _i, _len, _ref;

      _ref = field.fields;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        newData[field.name] = field.controller.map(model, newData[field.name]);
        this._mapFields(field, model, newData);
      }
      return newData;
    };

    /*
    */


    RootMapper.prototype.initializeModel = function(model, data) {
      var _this = this;

      model.reset = function(data) {
        var newData;

        newData = _this.map(model, data);
        return model.set(newData);
      };
      return model.reset(data);
    };

    /*
    */


    RootMapper.test = function(field) {
      return !field.parent;
    };

    return RootMapper;

  })(require("./base"));

  module.exports = RootMapper;

}).call(this);
