// Generated by CoffeeScript 1.6.2
(function() {
  var normalize, type;

  type = require("type-component");

  module.exports = normalize = function(options) {
    var normalizedOptions, optionName, t, value;

    if ((t = type(options)) === "string") {
      return {
        type: options
      };
    } else if (t === "array") {
      options = options[0];
      options.$collection = true;
    }
    normalizedOptions = {
      fields: {}
    };
    for (optionName in options) {
      value = options[optionName];
      if (optionName.substr(0, 1) === "$") {
        normalizedOptions[optionName.substr(1)] = value;
      } else {
        normalizedOptions.fields[optionName] = normalize(value);
      }
    }
    return normalizedOptions;
  };

}).call(this);
