// Generated by CoffeeScript 1.6.2
(function() {
  var MemoDictionary, memoize;

  memoize = require("./fn");

  MemoDictionary = (function() {
    /*
    */
    function MemoDictionary() {
      this._memos = {};
    }

    /*
    */


    MemoDictionary.prototype.call = function(key, options, next, fn) {
      var memo,
        _this = this;

      memo = this._memos[key];
      if (!memo) {
        memo = this._memos[key] = memoize((function(next) {
          return fn(next);
        }), options || {});
      }
      return memo(next);
    };

    /*
    */


    MemoDictionary.prototype.replaceHash = function(oldKey, newKey) {
      this._memos[newKey] = this._memos[oldKey];
      if (oldKey !== newKey) {
        return delete this._memos[oldKey];
      }
    };

    return MemoDictionary;

  })();

  module.exports = MemoDictionary;

}).call(this);
