// Generated by CoffeeScript 1.6.2
(function() {
  var MemoDictionary, memoize;

  memoize = require("./fn");

  MemoDictionary = (function() {
    /*
    */
    function MemoDictionary() {
      this._memos = {};
    }

    /*
    */


    MemoDictionary.prototype.call = function(key, hash, options, next, fn) {
      var memo,
        _this = this;

      memo = this._memos[key];
      if (memo) {
        if (memo.hash !== hash) {
          memo = void 0;
        }
      }
      if (!memo) {
        memo = this._memos[key] = {
          hash: hash,
          fn: memoize((function(next) {
            return fn(next);
          }), options || {})
        };
      }
      return memo.fn(next);
    };

    /*
    */


    MemoDictionary.prototype.replace = function(key, hash) {
      if (!this._memos[key]) {
        return;
      }
      return this._memos[key] = hash;
    };

    return MemoDictionary;

  })();

  module.exports = MemoDictionary;

}).call(this);
