// Generated by CoffeeScript 1.6.2
(function() {
  var flattenObj, type, _;

  type = require("type-component");

  _ = require("underscore");

  flattenObj = require("../utils/flattenObject");

  /*
  */


  module.exports = function(obj) {
    var hash, k, keys;

    keys = flattenObj({
      v: obj
    }, [], {});
    hash = [];
    for (k in keys) {
      hash.push(k, keys[k]);
    }
    return hash.join(":");
  };

}).call(this);
