// Generated by CoffeeScript 1.6.2
(function() {
  var BaseJSONifier;

  BaseJSONifier = (function() {
    /*
    */
    function BaseJSONifier(field) {
      this.field = field;
    }

    /*
    */


    BaseJSONifier.prototype.writeJSON = function(model, data) {};

    return BaseJSONifier;

  })();

  module.exports = BaseJSONifier;

}).call(this);
