// Generated by CoffeeScript 1.6.2
(function() {
  var JSONifier, Reference;

  Reference = require("./reference");

  JSONifier = require("./jsonify");

  module.exports = function(field) {
    if (field.options.ref) {
      return new Reference(field);
    }
    return new JSONifier(field);
  };

}).call(this);
