// Generated by CoffeeScript 1.6.2
(function() {
  var JSONify, dref, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dref = require("dref");

  JSONify = (function(_super) {
    __extends(JSONify, _super);

    function JSONify() {
      _ref = JSONify.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    JSONify.prototype.writeJSON = function(model, data) {
      if (data == null) {
        data = {};
      }
      return dref.set(data, this.field.path, model.get(this.field.path));
    };

    return JSONify;

  })(require("./base"));

  module.exports = JSONify;

}).call(this);
