// Generated by CoffeeScript 1.6.2
(function() {
  var NoJSONifier, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NoJSONifier = (function(_super) {
    __extends(NoJSONifier, _super);

    function NoJSONifier() {
      _ref = NoJSONifier.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    NoJSONifier.prototype.writeJSON = function(model, data) {};

    return NoJSONifier;

  })(require("./base"));

  module.exports = NoJSONifier;

}).call(this);
