// Generated by CoffeeScript 1.6.2
(function() {
  var RefJSONifier, dref, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dref = require("dref");

  RefJSONifier = (function(_super) {
    __extends(RefJSONifier, _super);

    function RefJSONifier() {
      _ref = RefJSONifier.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    RefJSONifier.prototype.writeJSON = function(model, data) {
      var ref;

      ref = model.get(this.field.path);
      return dref.set(data, this.field.path, ref != null ? ref.toJSON() : void 0);
    };

    return RefJSONifier;

  })(require("./base"));

  module.exports = RefJSONifier;

}).call(this);
