// Generated by CoffeeScript 1.6.2
(function() {
  var DataMapper, Transporter, Validator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Validator = require("../validator");

  DataMapper = require("../dataMapper");

  /*
   transports the model data to / from a server - restful
  */


  Transporter = (function(_super) {
    __extends(Transporter, _super);

    /*
    */


    function Transporter(field) {
      Transporter.__super__.constructor.call(this, field);
      this._validator = new Validator(field);
      this._dataMapper = new DataMapper(field);
    }

    /*
    */


    Transporter.prototype.initializeModel = function(model) {
      this._validator.initializeModel(model);
      return this._dataMapper.initializeModel(model);
    };

    /*
    */


    Transporter.prototype.load = function(model, next) {};

    /*
    */


    Transporter.prototype.save = function(model, next) {
      return this.validate(model, function(err, next) {});
    };

    /*
    */


    Transporter.prototype.validate = function(model, next) {
      return this._validator.validate(model, next);
    };

    return Transporter;

  })(require("../base"));

  module.exports = Transporter;

}).call(this);
