// Generated by CoffeeScript 1.6.2
(function() {
  var BaseController;

  BaseController = (function() {
    /*
    */
    function BaseController(field) {
      this.field = field;
    }

    /*
    */


    BaseController.prototype.initializeModel = function(model, data, options) {};

    return BaseController;

  })();

  module.exports = BaseController;

}).call(this);
