// Generated by CoffeeScript 1.6.2
(function() {
  var ModelMemoizer, memoize;

  memoize = require("./fn");

  /*
   caches remote values
  */


  ModelMemoizer = (function() {
    /*
    */
    function ModelMemoizer(model) {
      var _this = this;

      this.model = model;
      this.schema = model.schema;
      this._memoizedFields = {};
      this._maxAge = 1000 * 10;
      this.load = memoize((function(next) {
        return _this._load(next);
      }), {
        maxAge: !this._maxAge
      });
    }

    /*
    */


    ModelMemoizer.prototype.loadField = function(fieldName, next) {
      var field, memo;

      field = this.schema.field(fieldName, true);
      memo = this._memoizedFields[field.path];
      if (!memo) {
        memo = this._memoizedFields[field.path] = memoize((function(next) {
          return field.load(next);
        }), {
          maxAge: this._maxAge
        });
      }
      return memo(next);
    };

    /*
    */


    ModelMemoizer.prototype._load = function(next) {
      return this.schema.load(model, next);
    };

    return ModelMemoizer;

  })();

  module.exports = ModelMemoizer;

}).call(this);
