// Generated by CoffeeScript 1.6.2
(function() {
  var Field, Schema, controllers;

  Field = require("./field");

  controllers = require("./field/controllers");

  console.log(controllers);

  /*
  */


  Schema = (function() {
    /*
    */
    function Schema(definition, service) {
      this.service = service;
      this.field = new Field(definition);
      this._rootFieldController = controllers.initialize(this.field, this._createFieldController).controller;
    }

    /*
    */


    Schema.prototype.model = function(data, options) {};

    /*
    */


    Schema.prototype.collection = function(data, options) {};

    /*
    */


    Schema.prototype._createFieldController = function(field) {
      return new controllers.Transporter(field);
    };

    return Schema;

  })();

  module.exports = Schema;

}).call(this);
