// Generated by CoffeeScript 1.6.2
(function() {
  var each, flattenObject, type;

  type = require("type-component");

  each = function(obj, fn) {
    var i, k, v, _i, _len, _results, _results1;

    if (type(obj) === "array") {
      _results = [];
      for (i = _i = 0, _len = obj.length; _i < _len; i = ++_i) {
        v = obj[i];
        _results.push(fn("a" + i, v));
      }
      return _results;
    } else {
      _results1 = [];
      for (k in obj) {
        _results1.push(fn("o" + k, obj[k]));
      }
      return _results1;
    }
  };

  /*
  */


  module.exports = flattenObject = function(obj, path, keys) {
    each(obj, function(k, v) {
      var pt;

      pt = path.concat(k);
      if (/array|object/.test(type(v))) {
        return flattenObject(v, pt, keys);
      } else {
        return keys[pt.join(".")] = v;
      }
    });
    return keys;
  };

}).call(this);
