// Generated by CoffeeScript 1.6.2
(function() {
  var _unflatten;

  _unflatten = function(data, keys, currentData) {
    var k, nk, type;

    if (!keys.length) {
      return data;
    }
    k = keys.shift();
    type = k.substr(0, 1);
    if (!currentData) {
      currentData = type === "a" ? [] : {};
    }
    if (type === "a") {
      currentData.push(_unflatten(data, keys));
    }
    if (type === "o") {
      nk = k.substr(1);
      currentData[nk] = _unflatten(data, keys, currentData[nk]);
    }
    return currentData;
  };

  module.exports = function(data) {
    var currentData, key;

    currentData = void 0;
    for (key in data) {
      currentData = _unflatten(data[key], key.split("."), currentData);
    }
    return currentData;
  };

}).call(this);
