// Generated by CoffeeScript 1.6.2
(function() {
  var Mapper;

  Mapper = (function() {
    /*
    */
    function Mapper(schema) {
      this.schema = schema;
    }

    /*
    */


    Mapper.prototype.fetch = function(model, next) {
      return next();
    };

    return Mapper;

  })();

  module.exports = Mapper;

}).call(this);
