// Generated by CoffeeScript 1.6.2
(function() {
  var BaseVirtual;

  BaseVirtual = (function() {
    /*
    */
    function BaseVirtual(field) {
      this.field = field;
    }

    /*
    */


    BaseVirtual.prototype.fetch = function(model, next) {
      return next();
    };

    /*
     casts a value to another type
    */


    BaseVirtual.prototype.cast = function(model, value) {
      return value;
    };

    return BaseVirtual;

  })();

  module.exports = BaseVirtual;

}).call(this);
