// Generated by CoffeeScript 1.6.2
(function() {
  var BaseVirtual;

  BaseVirtual = (function() {
    /*
    */
    function BaseVirtual(schema) {
      this.schema = schema;
    }

    return BaseVirtual;

  })();

}).call(this);
