// Generated by CoffeeScript 1.6.2
(function() {
  var CastMap, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CastMap = (function(_super) {
    __extends(CastMap, _super);

    function CastMap() {
      _ref = CastMap.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    CastMap.prototype.constuctor = function(type) {};

    /*
    */


    CastMap.prototype.get = function(model, value) {};

    /*
    */


    CastMap.prototype.test = function(value) {};

    return CastMap;

  })(require("./base"));

}).call(this);
