// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionMap, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CollectionMap = (function(_super) {
    __extends(CollectionMap, _super);

    function CollectionMap() {
      _ref = CollectionMap.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    CollectionMap.prototype.get = function(value) {};

    return CollectionMap;

  })(require("./base"));

}).call(this);
