// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultVirtual, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  DefaultVirtual = (function(_super) {
    __extends(DefaultVirtual, _super);

    /*
    */


    function DefaultVirtual(field) {
      DefaultVirtual.__super__.constructor.call(this, field);
      this._createDefault = this._getDefaultFn(field.options["default"]);
    }

    /*
    */


    DefaultVirtual.prototype.fetch = function(model, next) {
      var _this = this;

      if ((model.get(this.field.path) != null) || !model.isNew()) {
        return next();
      }
      if (this._createDefault.length === 1) {
        return this._createDefault(function(err, value) {
          if (err) {
            return console.error(err);
          }
          model.set(_this.field.path, value);
          return next();
        });
      } else {
        model.set(this.field.path, this._createDefault());
        return next();
      }
    };

    /*
    */


    DefaultVirtual.prototype._getDefaultFn = function(def) {
      if (type(def) === "function") {
        return def;
      }
      return function() {
        return def;
      };
    };

    /*
    */


    DefaultVirtual.test = function(field) {
      return field.options["default"];
    };

    return DefaultVirtual;

  })(require("./base"));

  module.exports = DefaultVirtual;

}).call(this);
