// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultVirtual, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  DefaultVirtual = (function(_super) {
    __extends(DefaultVirtual, _super);

    /*
    */


    function DefaultVirtual(schema) {
      DefaultVirtual.__super__.constructor.call(this, schema);
      this._createDefault = this._getDefaultFn(schema.options["default"]);
    }

    /*
    */


    DefaultVirtual.prototype.fetch = function(model, next) {
      var _this = this;

      if (model.get(this.schema.path) != null) {
        return next();
      }
      if (model.isNew()) {
        if (this._createDefault.length === 1) {
          return this._createDefault(function(err, value) {
            if (err) {
              return console.error(err);
            }
            model.set(_this.schema.path, value);
            return next();
          });
        } else {
          model.set(this.schema.path, this._createDefault());
          return next();
        }
      } else {
        return this.child.fetch(model, next);
      }
    };

    /*
    */


    DefaultVirtual.prototype._getDefaultFn = function(def) {
      if (type(def) === "function") {
        return def;
      }
      return function() {
        return def;
      };
    };

    /*
    */


    DefaultVirtual.test = function(schema) {
      return schema.options["default"];
    };

    return DefaultVirtual;

  })(require("./base"));

  module.exports = DefaultVirtual;

}).call(this);
