// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultMapper, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  DefaultMapper = (function(_super) {
    __extends(DefaultMapper, _super);

    /*
    */


    function DefaultMapper(schema) {
      DefaultMapper.__super__.constructor.call(this, schema);
      this._createDefault = this._getDefaultFn(schema.options["default"]);
    }

    /*
    */


    DefaultMapper.prototype.get = function(model, value) {
      var _this = this;

      if (value != null) {
        return;
      }
      if (model.isNew()) {
        if (this._createDefault.length === 1) {
          return this._createDefault(function(err, value) {
            if (err) {
              return console.error(err);
            }
            return model.set(_this.schema.path, value);
          });
        } else {
          return model.set(this.schema.path, this._createDefault());
        }
      } else {
        return this.schema.fetch(model);
      }
    };

    /*
    */


    DefaultMapper.prototype._getDefaultFn = function(def) {
      if (type(def) === "function") {
        return def;
      }
      return function() {
        return def;
      };
    };

    /*
    */


    DefaultMapper.test = function(schema) {
      return schema.options["default"];
    };

    return DefaultMapper;

  })(require("./base"));

  module.exports = DefaultMapper;

}).call(this);
