// Generated by CoffeeScript 1.6.2
(function() {
  var FnVirtual,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ({
    _findFetch: function(schema) {
      var p;

      p = schema;
      while (p && !p.options.fetch) {
        p = p.parent;
      }
      return p != null ? p.options.fetch : void 0;
    }
  });

  FnVirtual = (function(_super) {
    __extends(FnVirtual, _super);

    /*
    */


    function FnVirtual(schema) {
      FnVirtual.__super__.constructor.call(this, schema);
      this._fetch = this._findFetch(schema);
    }

    /*
    */


    FnVirtual.prototype.fetch = function(model, next) {
      if (model.isNew() != null) {
        return next();
      }
      return this._fetch.call(model, function(err, result) {
        if (err != null) {
          return next(err);
        }
        return console.log(result);
      });
    };

    /*
    */


    FnVirtual.prototype._findFetch = function(schema) {
      var p;

      p = schema;
      while (p && !p.options.fetch) {
        p = p.parent;
      }
      return p != null ? p.options.fetch : void 0;
    };

    return FnVirtual;

  })(require("./base"));

  module.exports = FnVirtual;

}).call(this);
