// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionMapper, DefaultMapper, FnMapper, ReferenceMapper, Virtual, async;

  CollectionMapper = require("./collection");

  ReferenceMapper = require("./reference");

  DefaultMapper = require("./default");

  FnMapper = require("./fn");

  async = require("async");

  Virtual = (function() {
    /*
    */
    function Virtual(schema) {
      var ops;

      this.schema = schema;
      ops = this.schema.options;
      this._virtuals = [];
      if (ops["default"] != null) {
        this._virtuals.push(new DefaultMapper(this.schema));
      }
      this._virtuals.push(new FnMapper(this.schema));
      if (ops.multi) {
        this._virtuals.push(new CollectionMapper(this.schema));
      } else if (ops.ref) {
        this._virtuals.push(new ReferenceMapper(this.schema));
      }
    }

    /*
    */


    Virtual.prototype.fetch = function(model, next) {
      if (next == null) {
        next = function() {};
      }
      return async.forEach(this._virtuals, (function(mapper, next) {
        return mapper.fetch(model, next);
      }), next);
    };

    return Virtual;

  })();

  module.exports = Virtual;

}).call(this);
