// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionMapper, DefaultMapper, FnMapper, ReferenceMapper, Virtual;

  CollectionMapper = require("./collection");

  ReferenceMapper = require("./reference");

  DefaultMapper = require("./default");

  FnMapper = require("./fn");

  Virtual = (function() {
    /*
    */
    function Virtual(schema) {
      var ops;

      this.schema = schema;
      ops = this.schema.options;
      this._mappers = [];
      if (ops["default"] != null) {
        this._mappers.push(new DefaultMapper(this.schema));
      }
      if (ops.multi) {
        this._mappers.push(new CollectionMapper(this.schema));
      } else if (ops.ref) {
        this._mappers.push(new ReferenceMapper(this.schema));
      }
    }

    /*
    */


    Virtual.prototype.get = function(model) {
      var mapper, v, _i, _len, _ref;

      _ref = this._mappers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mapper = _ref[_i];
        v = mapper.get(model, v);
      }
      return v;
    };

    return Virtual;

  })();

  module.exports = Virtual;

}).call(this);
