// Generated by CoffeeScript 1.6.2
(function() {
  var RefMap;

  RefMap = (function() {
    /*
    */
    function RefMap(schema) {
      this.schema = schema;
    }

    /*
    */


    RefMap.prototype.map = function(model, value) {};

    return RefMap;

  })();

  module.exports = RefMap;

}).call(this);
