// Generated by CoffeeScript 1.6.2
(function() {
  var RequestVirtual;

  RequestVirtual = (function() {
    /*
    */
    function RequestVirtual() {}

    /*
    */


    RequestVirtual.test = function(schema) {
      return schema.options.fetch;
    };

    return RequestVirtual;

  })();

}).call(this);
