// Generated by CoffeeScript 1.6.2
(function() {
  var DataMapper,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DataMapper = (function(_super) {
    __extends(DataMapper, _super);

    /*
    */


    function DataMapper(field) {
      DataMapper.__super__.constructor.call(this, field);
    }

    /*
    */


    DataMapper.prototype.map = function(model, data) {};

    return DataMapper;

  })(require("../base"));

  module.exports = DataMapper;

}).call(this);
