// Generated by CoffeeScript 1.6.2
(function() {
  var BaseValidator;

  BaseValidator = (function() {
    /*
    */
    function BaseValidator(field) {
      this.field = field;
    }

    /*
    */


    BaseValidator.prototype.validate = function(model, next) {
      return next();
    };

    /*
    */


    return BaseValidator;

  })();

  module.exports = BaseValidator;

}).call(this);
