// Generated by CoffeeScript 1.6.2
(function() {
  var AnyFactory, GroupFactory;

  AnyFactory = require("../../../../factory/any");

  GroupFactory = require("../../../../factory/group");

  module.exports = new AnyFactory([new GroupFactory([require("./type"), require("./required"), require("./sub")], [], require("./group")), require("./none")]);

}).call(this);
