// Generated by CoffeeScript 1.6.2
(function() {
  var factories;

  factories = require("factories");

  module.exports = factories.any([factories.group([require("./type"), require("./required"), require("./sub")], [], require("./group")), require("./none")]);

}).call(this);
