// Generated by CoffeeScript 1.6.2
(function() {
  var GroupValidator, async,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require("async");

  GroupValidator = (function(_super) {
    __extends(GroupValidator, _super);

    /*
    */


    function GroupValidator(field, validators) {
      this.validators = validators;
      GroupValidator.__super__.constructor.call(this, field);
    }

    /*
    */


    GroupValidator.prototype.validate = function(model, next) {
      return async.forEach(this.validators, (function(validator, next) {
        return validator.validate(model, next);
      }), next);
    };

    return GroupValidator;

  })(require("./base"));

  module.exports = GroupValidator;

}).call(this);
