// Generated by CoffeeScript 1.6.2
(function() {
  var RequiredValidator, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RequiredValidator = (function(_super) {
    __extends(RequiredValidator, _super);

    function RequiredValidator() {
      _ref = RequiredValidator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RequiredValidator.prototype.validate = function(model, next) {
      var value;

      value = model.get(this.field.path);
      if (value != null) {
        return next();
      }
      return next(new Error("" + this.field.path + " is required"));
    };

    RequiredValidator.test = function(field) {
      return field.options.required;
    };

    return RequiredValidator;

  })(require("./base"));

  module.exports = RequiredValidator;

}).call(this);
