// Generated by CoffeeScript 1.6.2
(function() {
  var NoValidator, async, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require("async");

  NoValidator = (function(_super) {
    __extends(NoValidator, _super);

    function NoValidator() {
      _ref = NoValidator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NoValidator.prototype.validate = function(model, next) {
      return async.forEach(this.field.fields, (function(field, next) {
        return field._validator.validate(model, next);
      }), next);
    };

    NoValidator.test = function(field) {
      return field.fields.length;
    };

    return NoValidator;

  })(require("./base"));

  module.exports = NoValidator;

}).call(this);
