// Generated by CoffeeScript 1.6.2
(function() {
  var Validator, factory, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  factory = require("./decor/factory");

  Validator = (function(_super) {
    __extends(Validator, _super);

    function Validator() {
      _ref = Validator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Validator.prototype.name = "validator";

    /*
    */


    Validator.prototype.validate = function(model, next) {
      return this.rootField._validator.validate(model, next);
    };

    /*
    */


    Validator.prototype.prepareModel = function(model, data) {
      var _this = this;

      return model.validate = function(next) {
        return _this.validate(model, next);
      };
    };

    /*
    */


    Validator.prototype._createFieldDecorator = function(field) {
      return factory.create(field);
    };

    return Validator;

  })(require("../base"));

  module.exports = function(rootField) {
    return new Validator(rootField);
  };

}).call(this);
