// Generated by CoffeeScript 1.6.2
(function() {
  var ChangeWatcher;

  ChangeWatcher = (function() {
    /*
    */
    function ChangeWatcher(model) {
      this.model = model;
      this._values = {};
    }

    /*
    */


    ChangeWatcher.prototype.hasChanged = function(fieldName) {
      return this._values[fieldName] !== this.model.get(fieldName);
    };

    /*
    */


    ChangeWatcher.prototype.change = function(fieldName) {
      if (!this.hasChanged(fieldName)) {
        return false;
      }
      this._values[fieldName] = this.model.get(fieldName);
      return true;
    };

    return ChangeWatcher;

  })();

  module.exports = ChangeWatcher;

}).call(this);
