// Generated by CoffeeScript 1.6.2
(function() {
  var ChangeWatcher, dref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  dref = require("dref");

  ChangeWatcher = (function() {
    /*
    */
    function ChangeWatcher(model) {
      this.model = model;
      this._onChange = __bind(this._onChange, this);
      this.schema = this.model.schema;
      this.model.on("change", this._onChange);
      this._changes = {};
    }

    /*
    */


    ChangeWatcher.prototype._onChange = function(key, value) {
      return this._changes[key] = 1;
    };

    /*
    */


    ChangeWatcher.prototype.flushChangedKeys = function() {
      var key, keys;

      keys = [];
      for (key in this._changes) {
        keys.push(key);
      }
      this._changes = {};
      return keys;
    };

    return ChangeWatcher;

  })();

  module.exports = ChangeWatcher;

}).call(this);
