// Generated by CoffeeScript 1.6.2
(function() {
  var Collection, Payload, bindable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  Payload = require("./payload");

  Collection = (function(_super) {
    __extends(Collection, _super);

    /*
    */


    Collection.prototype.__isCollection = true;

    /*
    */


    function Collection(field) {
      this.field = field;
      Collection.__super__.constructor.call(this);
      this.transform().map(function(model) {
        return field.map(model);
      });
    }

    /*
    */


    Collection.prototype.hasChanged = function() {
      var item, _i, _len, _ref;

      _ref = this.source();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (item.hasChanged()) {
          return true;
        }
      }
      return false;
    };

    /*
    */


    Collection.prototype.fetch = function(next) {
      var _this = this;

      if (next == null) {
        next = function() {};
      }
      if (!this.field.isVirtual()) {
        return next();
      }
      return this.field.fetch(new Payload(this, "GET"), function(err, models) {
        if (err != null) {
          return next(err);
        }
        return _this.__reset(models);
      });
    };

    /*
    */


    Collection.prototype.save = function() {};

    /*
    */


    Collection.prototype.__reset = function(models) {
      return this.source(models);
    };

    return Collection;

  })(bindable.Collection);

  module.exports = Collection;

}).call(this);
