// Generated by CoffeeScript 1.6.2
(function() {
  var Fields, async;

  async = require("async");

  Fields = (function() {
    /*
    */
    function Fields(schema) {
      this.schema = schema;
      this._fields = {};
    }

    /*
    */


    Fields.prototype.add = function(field) {
      return this._fields[field.property] = field;
    };

    /*
    */


    Fields.prototype.get = function(name) {
      return this._fields[name];
    };

    /*
    */


    Fields.prototype.names = function() {
      return Object.keys(this._fields);
    };

    /*
    */


    Fields.prototype.fieldsToArray = function() {
      var fieldName, fields;

      fields = [];
      for (fieldName in this._fields) {
        fields.push(this.get(fieldName));
      }
      return fields;
    };

    /*
    */


    Fields.prototype.validate = function(model) {
      var err, errors, fieldName;

      errors = [];
      for (fieldName in this._fields) {
        err = this._fields[fieldName].validate(model);
        if (err) {
          errors.push(err);
        }
      }
      return errors.shift();
    };

    /*
    */


    Fields.prototype["default"] = function(data) {
      var d, fieldName, v;

      d = JSON.parse(JSON.stringify(data));
      for (fieldName in this._fields) {
        v = this._fields[fieldName]["default"](d[fieldName]);
        if (v != null) {
          d[fieldName] = v;
        }
      }
      return d;
    };

    /*
    */


    Fields.prototype.map = function(key, value) {
      var field;

      if (!(field = this.get(key))) {
        return value;
      }
      return field.map(value);
    };

    /*
    */


    Fields.prototype.save = function(payload, next) {
      var _this = this;

      return async.each(this.names(), (function(fieldName, next) {
        return _this.get(fieldName).save(payload, next);
      }), next);
    };

    return Fields;

  })();

  module.exports = Fields;

}).call(this);
