// Generated by CoffeeScript 1.6.2
(function() {
  var Linen, ModelPlugin, Route, mannequin;

  mannequin = require("mannequin");

  Route = require("./route");

  ModelPlugin = require("./modelPlugin");

  Linen = (function() {
    /*
    */
    function Linen(options) {
      var key;

      this.schemas = mannequin.dictionary();
      for (key in options.schemas) {
        ModelPlugin.plugin(this, this.schemas.register(key, options.schemas[key]));
      }
      this._route = new Route(options);
      this._transport = options.transport;
    }

    /*
    */


    Linen.prototype.item = function(path, query) {
      var modelBuilder;

      if (query == null) {
        query = {};
      }
      modelBuilder = this._modelBuilderByPath(path);
      return modelBuilder.linenBuilder.createItem(path, query);
    };

    /*
    */


    Linen.prototype.collection = function(path, query) {
      var modelBuilder;

      if (query == null) {
        query = {};
      }
      modelBuilder = this._modelBuilderByPath(path);
      return modelBuilder.linenBuilder.createCollection(path, query);
    };

    /*
    */


    Linen.prototype._request = function(options, next) {
      var path, ro;

      ro = options.item.requestOptions;
      return path = this._route.route(ro.path).path(ro);
    };

    /*
    */


    Linen.prototype._modelBuilderByPath = function(path) {
      return this.schemas.modelBuilder(this._route.route(path).schemaName);
    };

    return Linen;

  })();

  module.exports = function(options) {
    return new Linen(options);
  };

  module.exports.Route = Route;

}).call(this);
