// Generated by CoffeeScript 1.6.2
(function() {
  var Linen, schema;

  schema = require("./schema");

  Linen = (function() {
    /*
    */
    function Linen() {
      this._schemas = {};
    }

    /*
    */


    Linen.prototype.model = function(name, data) {
      if (!this._schemas[name]) {
        throw new Error("schema '" + name + "' does not exist");
      }
      return this._schemas[name].model(data);
    };

    /*
    */


    Linen.prototype.register = function(name, definition) {
      return this._schemas[name] = schema(definition, name, this);
    };

    return Linen;

  })();

  module.exports = function() {
    return new Linen();
  };

  module.exports.schema = schema;

}).call(this);
