// Generated by CoffeeScript 1.6.2
(function() {
  var Collection, ModelPlugin, async, cstep, dref, outcome, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Collection = require("bindable").Collection;

  cstep = require("cstep");

  dref = require("dref");

  outcome = require("outcome");

  async = require("async");

  _ = require("underscore");

  ModelPlugin = (function() {
    /*
    */
    function ModelPlugin(linen, modelBuilder) {
      this.linen = linen;
      this.modelBuilder = modelBuilder;
      this._modelBuilderCreateCollection = __bind(this._modelBuilderCreateCollection, this);
      this.schema = modelBuilder.schema;
      this._setup();
    }

    /*
    */


    ModelPlugin.prototype.createItem = function(path, data) {
      var model;

      if (data == null) {
        data = {};
      }
      data.requestOptions = {
        path: path
      };
      model = new this.modelClass(data);
      model.fetch();
      return model;
    };

    /*
    */


    ModelPlugin.prototype.createCollection = function(path, options) {
      var collection, isStatic, isVirtual, oldBind, oldReset, self, _ref, _ref1,
        _this = this;

      if (options == null) {
        options = {};
      }
      collection = new Collection();
      collection._fetched = false;
      self = this;
      isVirtual = (_ref = options.definition) != null ? _ref.$isVirtual : void 0;
      isStatic = (_ref1 = options.definition) != null ? _ref1.$isStatic : void 0;
      oldReset = collection.reset;
      collection.reset = function(source) {
        if (source.__isCollection) {
          source = source.source();
        }
        if (!isStatic) {
          this._fetchSource = source;
          source = [];
        }
        return oldReset.call(this, source);
      };
      collection.requestOptions = {
        path: path,
        params: options.params || {},
        query: options.query || {}
      };
      collection.transform().map(function(itemOrId) {
        var item;

        if (typeof itemOrId === "object") {
          item = itemOrId;
        } else {
          item = {
            _id: itemOrId
          };
        }
        return item;
      });
      collection.transform().postMap(function(item) {
        item.requestOptions = {
          path: path
        };
        return item;
      });
      collection.save = function(next) {
        return async.forEach(this.source(), (function(item, next) {
          return item.save(next);
        }), next);
      };
      oldBind = collection.bind;
      collection.bind = function() {
        this.fetch();
        return oldBind.apply(this, arguments);
      };
      collection.fetch = function(callback) {
        var onResult,
          _this = this;

        if (callback == null) {
          callback = (function() {});
        }
        this.once("loaded", callback);
        if (this._loading) {
          return;
        }
        this._loading = true;
        onResult = function() {
          _this._loading = false;
          return _this.emit("loaded");
        };
        if (isStatic) {
          return onResult();
        }
        if (!isVirtual) {
          return this._fetchReference(onResult);
        } else {
          return this._fetchVirtual(onResult);
        }
      };
      collection._fetchReference = function(next) {
        var _this = this;

        return async.forEach(this._fetchSource, (function(_id, next) {
          var i, item;

          if (~(i = _this.indexOf({
            _id: _id
          }))) {
            item = _this.at(i);
          } else {
            item = _this._transform({
              _id: _id
            });
          }
          return item.fetch(outcome.e(next).s(function() {
            if (!~i) {
              _this.push(item);
            }
            return next();
          }));
        }), next);
      };
      collection._fetchVirtual = function(callback) {
        return self._fetch({
          method: "GET",
          item: this
        }, callback);
      };
      return collection;
    };

    /*
    */


    ModelPlugin.prototype._modelBuilderCreateCollection = function(item, definition) {
      var collectionName, path, schemaName;

      schemaName = definition.options.$ref;
      collectionName = definition.key;
      path = definition.options.$path || [item.requestOptions.path, definition.key].join(".");
      return this.createCollection(path, {
        definition: definition
      });
    };

    /*
    */


    ModelPlugin.prototype._fetch = function(options, callback) {
      return this.linen._request(options, callback);
    };

    /*
    */


    ModelPlugin.prototype._setup = function() {
      var modelBuilder, name, oldInitData, oldSet, self;

      self = this;
      modelBuilder = this.modelBuilder = this.schema.modelBuilder;
      modelBuilder.createCollection = this._modelBuilderCreateCollection;
      this.modelClass = modelBuilder.getClass();
      name = modelBuilder.name;
      oldInitData = this.modelClass.prototype._initData;
      modelBuilder.methods._initData = function(data) {
        if (typeof data === "string") {
          data = {
            _id: data
          };
          this.requestOptions = {};
        } else {
          data = data;
          this.requestOptions = data.requestOptions || {};
          delete data.requestOptions;
        }
        return oldInitData.call(this, data);
      };
      oldSet = this.modelClass.prototype._set;
      modelBuilder.methods._set = function(key, value) {
        oldSet.apply(this, arguments);
        if (!this._update) {
          this._update = {};
        }
        return dref.set(this._update, key, value);
      };
      modelBuilder.methods.hydrate = function(key, value) {
        this.set.apply(this, arguments);
        this._update = {};
        return this;
      };
      modelBuilder.methods.fetch = function(next) {
        var _this = this;

        if (next == null) {
          next = (function() {});
        }
        this.once("loaded", next);
        if (this._loading) {
          return;
        }
        this._loading = true;
        return this._fetch(outcome.e(next).s(function(result) {
          return _this._loading = false;
        }));
      };
      modelBuilder.methods._fetch = cstep(function(next) {
        var _ref,
          _this = this;

        this.requestOptions[name] = this.get("_id");
        this.requestOptions.path = ((_ref = this.ownerDefinition) != null ? _ref.options.$path : void 0) || this.requestOptions.path || name;
        return self._fetch({
          method: "GET",
          item: this,
          one: true
        }, outcome.e(next).s(function(result) {
          _this.hydrate(result);
          _this.emit("loaded");
          return next();
        }));
      });
      modelBuilder.methods.isNew = function() {
        return !get("_id");
      };
      modelBuilder.pre("save", cstep(function(next) {
        return this.validate(next);
      }));
      modelBuilder.pre("save", function(next) {
        if (this.isNew()) {
          return self._fetch({
            method: "POST",
            item: this,
            data: this._update
          }, next);
        } else if (_.keys(this._update).length) {
          return self._fetch({
            method: "PUT",
            item: this,
            data: this._update
          }, next);
        }
      });
      return modelBuilder.pre("remove", cstep(function(next) {
        if (this.isNew()) {
          return next(new Error("cannot remove a new item"));
        }
        return self._fetch({
          method: "DELETE",
          item: this
        }, next);
      }));
    };

    return ModelPlugin;

  })();

  exports.plugin = function(linen, modelBuilder) {
    var plugin;

    plugin = new ModelPlugin(linen, modelBuilder);
    modelBuilder.schema.linenBuilder = plugin;
    modelBuilder.linenBuilder = plugin;
    return plugin;
  };

}).call(this);
