// Generated by CoffeeScript 1.6.2
(function() {
  var Model, bindable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  Model = (function(_super) {
    __extends(Model, _super);

    /*
    */


    function Model(schema) {
      this.schema = schema;
      Model.__super__.constructor.call(this);
    }

    /*
     called when a property is being watched on this model
    */


    Model.prototype._watching = function(property) {
      return this.schema.fetch(this, property);
    };

    /*
    */


    Model.prototype.reset = function(data) {
      this.set(data);
      return this.changed = [];
    };

    /*
    */


    Model.prototype.get = function(key) {
      var _ref;

      return (_ref = Model.__super__.get.call(this, key)) != null ? _ref : this.schema.vget(this, key);
    };

    /*
    */


    Model.prototype._set = function(key, value) {
      return Model.__super__._set.call(this, key, this.schema.vset(this, key, value));
    };

    /*
    */


    Model.prototype.isNew = function() {
      return !this.get("_id");
    };

    /*
    */


    Model.prototype.fetch = function(next) {
      return this.schema.fetch(this);
    };

    /*
    */


    Model.prototype.validate = function(next) {
      return this.schema.validate(this);
    };

    /*
    */


    Model.prototype.save = function(next) {
      return this.schema.save(this);
    };

    return Model;

  })(bindable.Object);

  module.exports = Model;

}).call(this);
