// Generated by CoffeeScript 1.6.2
(function() {
  var Payload;

  Payload = (function() {
    /*
    */
    function Payload(target, method, changed) {
      var key;

      this.target = target;
      this.method = method;
      this.changed = changed != null ? changed : {};
      this.data = {};
      for (key in changed) {
        this.data[key] = changed.nv;
      }
    }

    return Payload;

  })();

  module.exports = Payload;

}).call(this);
