// Generated by CoffeeScript 1.6.2
(function() {
  var Payload;

  Payload = (function() {
    /*
    */
    function Payload() {
      this.data = {
        changed: []
      };
    }

    /*
    */


    Payload.prototype.changed = function(changed) {
      var cv, data, _i, _len;

      data = {};
      for (_i = 0, _len = changed.length; _i < _len; _i++) {
        cv = changed[_i];
        data[cv.key] = cv.nv;
      }
      this.data.data = data;
      this.data.changed = changed;
      return this;
    };

    /*
    */


    Payload.prototype.method = function(method) {
      this.data.method = method;
      return this;
    };

    /*
    */


    Payload.prototype.collection = function(collection) {
      this.data.collection = collection;
      return this.model(collection.owner);
    };

    /*
    */


    Payload.prototype.model = function(model) {
      this.data.model = model;
      this.data.data = model.toJSON();
      return this;
    };

    /*
    */


    Payload.prototype.target = function(model) {
      this.data.target = model;
      this.data.data = model.toJSON();
      return this;
    };

    /*
    */


    Payload.prototype.toJSON = function() {
      return this.data;
    };

    return Payload;

  })();

  Object.keys(Payload.prototype).forEach(function(method) {
    return exports[method] = function(value) {
      var p;

      p = new Payload();
      return p[method].call(p, value);
    };
  });

}).call(this);
