// Generated by CoffeeScript 1.6.2
(function() {
  var Payload;

  Payload = (function() {
    /*
    */
    function Payload(model, method, changed) {
      this.model = model;
      this.method = method;
      this.changed = changed != null ? changed : {};
    }

    return Payload;

  })();

  module.exports = Payload;

}).call(this);
