// Generated by CoffeeScript 1.6.2
(function() {
  var PayloadData;

  PayloadData = (function() {
    /*
    */
    function PayloadData(payload, keys) {
      var key, v, _i, _len;

      this.payload = payload;
      this.keys = keys != null ? keys : [];
      v = {};
      if (this.keys.length) {
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          v[key] = payload.model.get(key);
        }
      } else {
        v = payload.model.get();
      }
      this.value = v;
    }

    return PayloadData;

  })();

  module.exports = PayloadData;

}).call(this);
