// Generated by CoffeeScript 1.6.2
(function() {
  var Schema, Schemas, comerr;

  Schema = require("./schema");

  comerr = require("comerr");

  Schemas = (function() {
    /*
    */
    function Schemas(linen) {
      this.linen = linen;
      this._schemas = {};
    }

    /*
    */


    Schemas.prototype.add = function(schemaOptions) {
      if (this._schemas[schemaOptions.name]) {
        throw new comerr.AlreadyExists("schema " + schemaOptions.name + " already exists");
      }
      return this._schemas[schemaOptions.name] = new Schema(this.linen, schemaOptions);
    };

    /*
    */


    Schemas.prototype.get = function(name) {
      return this._schemas[name];
    };

    /*
    */


    Schemas.prototype.model = function(name, options) {
      return this._vExists(name).model(options);
    };

    /*
    */


    Schemas.prototype.collection = function(name) {
      return this._vExists(name).collection();
    };

    /*
    */


    Schemas.prototype._vExists = function(name) {
      var schema;

      if (!(schema = this._schemas[name])) {
        throw new comerr.NotFound("schema " + name + " doesn't exist");
      }
      return schema;
    };

    return Schemas;

  })();

  module.exports = Schemas;

}).call(this);
