// Generated by CoffeeScript 1.6.2
(function() {
  var BaseMapper;

  BaseMapper = (function() {
    /*
    */
    function BaseMapper(field) {
      this.field = field;
      this._fields = field.fields;
    }

    /*
    */


    BaseMapper.prototype.map = function(model, data) {
      return data;
    };

    /*
    */


    BaseMapper.prototype.prepareModel = function(model, data) {};

    return BaseMapper;

  })();

  module.exports = BaseMapper;

}).call(this);
