// Generated by CoffeeScript 1.6.2
/*
  createdAt: {
    $default: Date.now
  }
*/


(function() {
  var CastMapper,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CastMapper = (function(_super) {
    __extends(CastMapper, _super);

    /*
    */


    function CastMapper(field) {
      CastMapper.__super__.constructor.call(this, field);
      this._cast = this._caster(field.options.type);
    }

    /*
    */


    CastMapper.prototype.map = function(model, data) {
      if (data == null) {
        return void 0;
      }
      return this._cast(data);
    };

    /*
    */


    CastMapper.prototype._caster = function(type) {
      if (type === "string") {
        return function(value) {
          return String(value);
        };
      }
      if (type === "number") {
        return function(value) {
          return Number(value);
        };
      }
      if (type === "boolean") {
        return function(value) {
          return !!value;
        };
      }
      return function(value) {
        return value;
      };
    };

    /*
    */


    CastMapper.test = function(field) {
      return !!field.options.type;
    };

    return CastMapper;

  })(require("./base"));

  module.exports = CastMapper;

}).call(this);
