// Generated by CoffeeScript 1.6.2
(function() {
  var GroupMapper,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  GroupMapper = (function(_super) {
    __extends(GroupMapper, _super);

    /*
    */


    function GroupMapper(field, _mappers) {
      this.field = field;
      this._mappers = _mappers;
    }

    /*
    */


    GroupMapper.prototype.map = function(model, data) {
      var mapper, newData, _i, _len, _ref;

      newData = data;
      _ref = this._mappers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mapper = _ref[_i];
        newData = mapper.map(model, newData);
      }
      return newData;
    };

    /*
    */


    GroupMapper.prototype.normalize = function(model) {
      var data, mapper, _i, _len, _ref;

      _ref = this._mappers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mapper = _ref[_i];
        data = mapper.normalize(model, data);
      }
      return data;
    };

    return GroupMapper;

  })(require("./base"));

  module.exports = GroupMapper;

}).call(this);
