// Generated by CoffeeScript 1.6.2
(function() {
  var NoMapper, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NoMapper = (function(_super) {
    __extends(NoMapper, _super);

    function NoMapper() {
      _ref = NoMapper.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    NoMapper.test = function() {
      return true;
    };

    return NoMapper;

  })(require("./base"));

  module.exports = NoMapper;

}).call(this);
