// Generated by CoffeeScript 1.6.2
(function() {
  var BaseLinenCollection, flatstack,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  flatstack = require("flatstack");

  BaseLinenCollection = (function(_super) {
    __extends(BaseLinenCollection, _super);

    /*
    */


    function BaseLinenCollection(field) {
      this.field = field;
      BaseLinenCollection.__super__.constructor.call(this);
      this._callstack = flatstack();
      this.on({
        insert: this._persistInsert,
        remove: this._persistRemove,
        reset: this._persistReset
      });
    }

    /*
    */


    BaseLinenCollection.prototype.clear = function() {
      return this.source([]);
    };

    /*
    */


    BaseLinenCollection.prototype._watching = function(property) {};

    /*
    */


    BaseLinenCollection.prototype._persistInsert = function(model) {};

    /*
    */


    BaseLinenCollection.prototype._persistRemove = function(model) {};

    /*
    */


    BaseLinenCollection.prototype._persistReset = function() {};

    return BaseLinenCollection;

  })(require("bindable").Collection);

  module.exports = BaseLinenCollection;

}).call(this);
