// Generated by CoffeeScript 1.6.2
(function() {
  var ModelCollection,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ModelCollection = (function(_super) {
    __extends(ModelCollection, _super);

    /*
    */


    ModelCollection.prototype.__collectionType = "model";

    /*
    */


    function ModelCollection(field) {
      var _this = this;

      ModelCollection.__super__.constructor.call(this, field);
      this.transform().map(function(value) {
        var m;

        if (value.__isModel) {
          return value;
        }
        m = field.linen.model(field.options.ref, value);
        m.owner = _this.owner;
        return m;
      });
    }

    /*
    */


    ModelCollection.prototype.clear = function() {
      var model, source, _i, _len, _results;

      source = this.source().concat();
      _results = [];
      for (_i = 0, _len = source.length; _i < _len; _i++) {
        model = source[_i];
        _results.push(model.remove());
      }
      return _results;
    };

    /*
    */


    ModelCollection.prototype.reset = function(source) {
      return ModelCollection.__super__.reset.call(this, source);
    };

    /*
    */


    ModelCollection.prototype.load = function(next) {};

    /*
    */


    ModelCollection.prototype.save = function(next) {};

    return ModelCollection;

  })(require("./base"));

  module.exports = ModelCollection;

}).call(this);
