// Generated by CoffeeScript 1.6.2
(function() {
  var ModelCollection, bindable, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  ModelCollection = (function(_super) {
    __extends(ModelCollection, _super);

    function ModelCollection() {
      _ref = ModelCollection.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return ModelCollection;

  })(bindable.Collection);

  module.exports = ModelCollection;

}).call(this);
