// Generated by CoffeeScript 1.6.2
(function() {
  var PrimitiveCollection, bindable, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  PrimitiveCollection = (function(_super) {
    __extends(PrimitiveCollection, _super);

    function PrimitiveCollection() {
      _ref = PrimitiveCollection.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return PrimitiveCollection;

  })(bindable.Collection);

  module.exports = PrimitiveCollection;

}).call(this);
