// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultMapper, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  DefaultMapper = (function(_super) {
    __extends(DefaultMapper, _super);

    /*
    */


    function DefaultMapper(schema) {
      DefaultMapper.__super__.constructor.call(this, schema);
      this._createDefault = this._getDefaultFn(schema.options["default"]);
    }

    /*
    */


    DefaultMapper.prototype.map = function(value) {
      return value != null ? value : this._createDefault();
    };

    /*
    */


    DefaultMapper.prototype._getDefaultFn = function(def) {
      if (type(def) === "function") {
        return def;
      }
      return function() {
        return def;
      };
    };

    /*
    */


    DefaultMapper.test = function(schema) {
      return schema.options["default"];
    };

    return DefaultMapper;

  })(require("./base"));

  module.exports = DefaultMapper;

}).call(this);
