// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionMapper, DefaultMapper, FnMapper, Mapper, ReferenceMapper;

  CollectionMapper = require("./collection");

  ReferenceMapper = require("./reference");

  DefaultMapper = require("./default");

  FnMapper = require("./fn");

  Mapper = (function() {
    /*
    */
    function Mapper(schema) {
      var ops;

      this.schema = schema;
      ops = this.schema.options;
      this._mappers = [];
      if (ops["default"]) {
        this._mappers.push(new DefaultMapper(this.schema));
      }
      if (ops.multi) {
        this._mappers.push(new CollectionMapper(this.schema));
      } else if (ops.ref) {
        this._mappers.push(new ReferenceMapper(this.schema));
      }
    }

    /*
    */


    Mapper.prototype.map = function(value) {
      var mapper, v, _i, _len, _ref;

      v = value;
      _ref = this._mappers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mapper = _ref[_i];
        v = mapper.map(v);
      }
      return v;
    };

    return Mapper;

  })();

  module.exports = Mapper;

}).call(this);
