// Generated by CoffeeScript 1.6.2
(function() {
  var BaseFetcher;

  BaseFetcher = (function() {
    /*
    */
    function BaseFetcher(field) {
      this.field = field;
    }

    /*
    */


    BaseFetcher.prototype.fetch = function(payload, next) {
      return next();
    };

    /*
    */


    BaseFetcher.prototype.toObject = function(model, data) {
      return data;
    };

    return BaseFetcher;

  })();

  module.exports = BaseFetcher;

}).call(this);
