// Generated by CoffeeScript 1.6.2
(function() {
  var FnFetch, NoFetch, RefFetch;

  FnFetch = require("./fn");

  RefFetch = require("./reference");

  NoFetch = require("./none");

  module.exports = function(field) {
    if (field.options.fetch) {
      return new FnFetch(field);
    }
    return new NoFetch();
  };

}).call(this);
