// Generated by CoffeeScript 1.6.2
(function() {
  var FnFetch, InheritFetch, RefFetch;

  FnFetch = require("./fn");

  RefFetch = require("./reference");

  InheritFetch = require("./inherit");

  module.exports = function(field) {
    if (field.options.fetch) {
      return new FnFetch(field);
    }
    if (field.options.ref) {
      return new RefFetch(field);
    }
    return new InheritFetch(field);
  };

}).call(this);
