// Generated by CoffeeScript 1.6.2
(function() {
  var FnFetch;

  FnFetch = (function() {
    /*
    */
    function FnFetch(field) {
      this.field = field;
    }

    /*
    */


    FnFetch.prototype.fetch = function(payload, next) {
      var fn, method,
        _this = this;

      method = payload.method;
      if (!(fn = this.field.options.fetch[method])) {
        return next(new Error("method \"" + method + "\" on \"" + this.field.path + "\" doesn't exist"));
      }
      payload.field = this.field;
      return fn.call(payload.model, payload, function(err, result) {
        if (result == null) {
          result = {};
        }
        return setTimeout((function() {
          if (err != null) {
            return next(err);
          }
          if (!_this.field.parent) {
            payload.model.set(result);
          } else {
            payload.model.set(_this.field.path, result);
          }
          return next();
        }), 1);
      });
    };

    return FnFetch;

  })();

  module.exports = FnFetch;

}).call(this);
