// Generated by CoffeeScript 1.6.2
(function() {
  var InheritFetch, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InheritFetch = (function(_super) {
    __extends(InheritFetch, _super);

    function InheritFetch() {
      _ref = InheritFetch.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    InheritFetch.prototype.fetch = function(payload, next) {
      if (!this.field.parent || payload.method !== "get") {
        return next();
      }
      return this.field.parent.fetch(payload, next);
    };

    return InheritFetch;

  })(require("./base"));

  module.exports = InheritFetch;

}).call(this);
