// Generated by CoffeeScript 1.6.2
(function() {
  var InheritFetch;

  InheritFetch = (function() {
    /*
    */
    function InheritFetch(field) {
      this.field = field;
    }

    /*
    */


    InheritFetch.prototype.fetch = function(payload, next) {
      if (!this.field.parent) {
        return next();
      }
      return this.field.parent.fetch(payload, next);
    };

    return InheritFetch;

  })();

  module.exports = InheritFetch;

}).call(this);
