// Generated by CoffeeScript 1.6.2
(function() {
  var NoFetch;

  NoFetch = (function() {
    function NoFetch() {}

    /*
    */


    NoFetch.prototype.fetch = function(payload, next) {
      return next();
    };

    return NoFetch;

  })();

  module.exports = NoFetch;

}).call(this);
