// Generated by CoffeeScript 1.6.2
(function() {
  var RefFetch, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RefFetch = (function(_super) {
    __extends(RefFetch, _super);

    function RefFetch() {
      _ref = RefFetch.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    RefFetch.prototype.fetch = function(payload, next) {
      var ref;

      ref = payload.model.get(this.field.path);
      if (ref == null) {
        return next();
      }
      if (payload.method === "get") {
        return ref.load(next);
      } else if (/put|post/.test(payload.method)) {
        return ref.save(next);
      } else {
        return next();
      }
    };

    return RefFetch;

  })(require("./base"));

  module.exports = RefFetch;

}).call(this);
