// Generated by CoffeeScript 1.6.2
(function() {
  var AnyFactory, tarray, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  tarray = require("toarray");

  AnyFactory = (function(_super) {
    __extends(AnyFactory, _super);

    function AnyFactory() {
      _ref = AnyFactory.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    AnyFactory.prototype.create = function(option) {
      var factory, items, _i, _len, _ref1;

      items = [];
      _ref1 = this._factories;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        factory = _ref1[_i];
        if (factory.test(option)) {
          items = items.concat(toarray(factory.create(options)));
        }
      }
      return items;
    };

    return AnyFactory;

  })(require("./factory"));

  module.exports = AnyFactory;

}).call(this);
