// Generated by CoffeeScript 1.6.2
(function() {
  var BaseFactory;

  BaseFactory = (function() {
    function BaseFactory() {}

    /*
    */


    BaseFactory.prototype.__isFactory = true;

    return BaseFactory;

  })();

  module.exports = BaseFactory;

}).call(this);
