// Generated by CoffeeScript 1.6.2
(function() {
  var ClassFactory,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ClassFactory = (function(_super) {
    __extends(ClassFactory, _super);

    /*
    */


    function ClassFactory(_class) {
      this._class = _class;
    }

    /*
    */


    ClassFactory.prototype.test = function(options) {
      return this._class.test(options);
    };

    /*
    */


    ClassFactory.prototype.create = function(options) {
      return new this._class(options);
    };

    return ClassFactory;

  })(require("./base"));

  module.exports = ClassFactory;

}).call(this);
