// Generated by CoffeeScript 1.6.2
(function() {
  var EitherFactory, toarray, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  toarray = require("toarray");

  EitherFactory = (function(_super) {
    __extends(EitherFactory, _super);

    function EitherFactory() {
      _ref = EitherFactory.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    EitherFactory.prototype.create = function(options) {
      var factory, _i, _len, _ref1;

      _ref1 = this._factories;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        factory = _ref1[_i];
        if (factory.test(options)) {
          return factory.create(options);
        }
      }
      return void 0;
    };

    return EitherFactory;

  })(require("./factory"));

  module.exports = EitherFactory;

}).call(this);
