// Generated by CoffeeScript 1.6.2
(function() {
  var ClassFactory, FactoryFactory, FnFactory, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ClassFactory = require("./class");

  type = require("type-component");

  FnFactory = require("./fn");

  FactoryFactory = (function(_super) {
    __extends(FactoryFactory, _super);

    /*
    */


    function FactoryFactory() {}

    /*
    */


    FactoryFactory.prototype.create = function(data) {
      var t;

      if ((t = type(data)) === "function") {
        if (data.prototype.constructor) {
          if (data.create && data.test) {
            return data;
          } else {
            return new ClassFactory(data);
          }
        }
        return new FnFactory(data);
      }
      return data;
    };

    return FactoryFactory;

  })(require("./base"));

  module.exports = new FactoryFactory();

}).call(this);
