// Generated by CoffeeScript 1.6.2
(function() {
  var Validator, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Validator = (function(_super) {
    __extends(Validator, _super);

    function Validator() {
      _ref = Validator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Validator.prototype.validate = function(model, next) {};

    return Validator;

  })(require("../base"));

  module.exports = Validator;

}).call(this);
