// Generated by CoffeeScript 1.6.2
(function() {
  var ModelCollection, bindable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  ModelCollection = (function(_super) {
    __extends(ModelCollection, _super);

    /*
    */


    function ModelCollection(field, owner) {
      var _this = this;

      this.field = field;
      this.owner = owner;
      ModelCollection.__super__.constructor.call(this);
      this.transform().map(function(v) {
        return _this.field._refMapper.map(_this.owner, v);
      });
    }

    /*
    */


    ModelCollection.prototype.model = function(data) {
      var model,
        _this = this;

      if (data == null) {
        data = {};
      }
      model = this.field._refMapper.map(data, data);
      model.owner = this;
      model.once("save", function() {
        return _this.push(model);
      });
      return model;
    };

    return ModelCollection;

  })(bindable.Collection);

  module.exports = ModelCollection;

}).call(this);
