// Generated by CoffeeScript 1.6.2
(function() {
  var Transporter, dataMapper, type, validator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  validator = require("../validator");

  dataMapper = require("../dataMapper");

  type = require("type-component");

  /*
   transports the model data to / from a server - restful
  */


  Transporter = (function(_super) {
    __extends(Transporter, _super);

    /*
    */


    Transporter.prototype.name = "transporter";

    /*
    */


    function Transporter(rootField) {
      Transporter.__super__.constructor.call(this, rootField);
      this._validator = validator(rootField);
      this._dataMapper = dataMapper(rootField);
    }

    /*
    */


    Transporter.prototype.prepareModel = function(model, data) {
      if (type(data) === "string") {
        data = {
          _id: data
        };
      }
      this._validator.prepareModel(model, data);
      return this._dataMapper.prepareModel(model, data);
    };

    /*
    */


    Transporter.prototype.map = function(model, data) {
      return this._dataMapper.map(model, data);
    };

    /*
    */


    Transporter.prototype.load = function(model, next) {};

    /*
    */


    Transporter.prototype.save = function(model, next) {
      return this.validate(model, function(err, next) {});
    };

    /*
    */


    Transporter.prototype.validate = function(model, next) {
      return this._validator.validate(model, next);
    };

    return Transporter;

  })(require("../base"));

  module.exports = function(field) {
    return new Transporter(field);
  };

}).call(this);
