// Generated by CoffeeScript 1.6.2
(function() {
  var MemoDictionary, Transporter, async, dataMapper, transporterFactory, type, validator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  validator = require("../validator");

  dataMapper = require("../dataMapper");

  type = require("type-component");

  async = require("async");

  MemoDictionary = require("./memoize/dictionary");

  transporterFactory = require("./decor/factory");

  /*
   transports the model data to / from a server - restful
  */


  Transporter = (function(_super) {
    __extends(Transporter, _super);

    /*
    */


    Transporter.prototype.name = "transporter";

    /*
    */


    function Transporter(rootField) {
      Transporter.__super__.constructor.call(this, rootField);
      this._validator = validator(rootField);
      this._dataMapper = dataMapper(rootField);
    }

    /*
    */


    Transporter.prototype.prepareModel = function(model, data) {
      var _this = this;

      if (type(data) === "string") {
        data = {
          _id: data
        };
      }
      this._validator.prepareModel(model, data);
      this._dataMapper.prepareModel(model, data);
      model._memos = new MemoDictionary();
      model.load = function(next) {
        return _this.load(model, next);
      };
      model.save = function(next) {
        return _this.save(model, next);
      };
      return model.on("watching", function(property) {
        var _ref;

        if (model.get(property) != null) {
          return;
        }
        return (_ref = _this.rootField.getField(property, true)) != null ? _ref._transporter.request({
          model: model,
          method: "get"
        }, function() {}) : void 0;
      });
    };

    /*
    */


    Transporter.prototype.map = function(model, data) {
      return this._dataMapper.map(model, data);
    };

    /*
    */


    Transporter.prototype.load = function(model, next) {
      return this._request({
        model: model,
        method: "get"
      }, next);
    };

    /*
    */


    Transporter.prototype.save = function(model, next) {
      var _this = this;

      return this.validate(model, function(err) {
        if (err != null) {
          return next(err);
        }
        return _this._request({
          model: model,
          method: "set"
        }, next);
      });
    };

    /*
    */


    Transporter.prototype._request = function(options, next) {
      return async.forEach(this._decorators, (function(decor, next) {
        return decor.request(options, next);
      }), next);
    };

    /*
    */


    Transporter.prototype.validate = function(model, next) {
      return this._validator.validate(model, next);
    };

    /*
    */


    Transporter.prototype._createFieldDecorator = function(field) {
      return transporterFactory.create(field);
    };

    return Transporter;

  })(require("../base"));

  module.exports = function(field) {
    return new Transporter(field);
  };

}).call(this);
