// Generated by CoffeeScript 1.6.2
(function() {
  var Payload;

  Payload = (function() {
    /*
    */
    function Payload(options) {
      this.options = options != null ? options : {};
    }

    /*
    */


    Payload.prototype.method = function(method) {
      this.options.method = method;
      return this;
    };

    /*
    */


    Payload.prototype.model = function(model) {
      this.options.model = model;
      return this;
    };

    /*
    */


    Payload.prototype.body = function(body) {
      this.options.body = body;
      return this;
    };

    /*
    */


    Payload.prototype.params = function(params) {
      this.options.params = params;
      return this;
    };

    /*
    */


    Payload.prototype.query = function(query) {
      this.options.query = query;
      return this;
    };

    /*
    */


    Payload.prototype.toObject = function() {
      return this.options;
    };

    return Payload;

  })();

  /*
  */


  exports.model = function(model) {
    return new Payload().model(model);
  };

}).call(this);
