// Generated by CoffeeScript 1.6.2
(function() {
  var FnValidator, type;

  type = require("type-component");

  FnValidator = (function() {
    /*
    */
    function FnValidator(_tester) {
      this._tester = _tester;
    }

    /*
    */


    FnValidator.prototype.validate = function(value, next) {
      return this._tester(value, next);
    };

    /*
    */


    FnValidator.test = function(options) {
      return type(options) === "function";
    };

    return FnValidator;

  })();

  module.exports = FnValidator;

}).call(this);
