// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    Validator: require("./validator"),
    DataMapper: require("./dataMapper"),
    Transporter: require("./transporter"),
    initialize: function(field, createController) {
      var _i, _len, _ref;

      _ref = field.flatten();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        field.controller = createController(field);
      }
      return field;
    }
  };

}).call(this);
