// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultMap, type;

  type = require("type-component");

  DefaultMap = (function() {
    /*
    */
    function DefaultMap(field) {
      this.field = field;
      this._default = this._fixDefault(field.options["default"]);
    }

    /*
    */


    DefaultMap.prototype.map = function(model, value) {
      if (!model.isNew()) {
        return value;
      }
      return value != null ? value : this._default();
    };

    /*
    */


    DefaultMap.prototype._fixDefault = function(def) {
      if (type(def) === "function") {
        return def;
      } else {
        return function() {
          return def;
        };
      }
    };

    return DefaultMap;

  })();

  module.exports = DefaultMap;

}).call(this);
