// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultMap, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  DefaultMap = (function(_super) {
    __extends(DefaultMap, _super);

    /*
    */


    function DefaultMap(field) {
      this.field = field;
      this._default = this._fixDefault(field.options["default"]);
    }

    /*
    */


    DefaultMap.prototype.map = function(model, value) {
      if (!model.isNew()) {
        return value;
      }
      return value != null ? value : this._default();
    };

    /*
    */


    DefaultMap.prototype._fixDefault = function(def) {
      if (type(def) === "function") {
        return def;
      } else {
        return function() {
          return def;
        };
      }
    };

    return DefaultMap;

  })(require("./base"));

  module.exports = DefaultMap;

}).call(this);
