// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionMap, DefaultMap, FnMap, GetterSetterMap, NoMap, ReferenceMap;

  GetterSetterMap = require("./gs");

  DefaultMap = require("./default");

  ReferenceMap = require("./reference");

  NoMap = require("./none");

  FnMap = require("./fn");

  CollectionMap = require("./collection");

  module.exports = function(field) {
    if (field.options.collection) {
      return new CollectionMap(field);
    }
    if (field.options["default"] != null) {
      return new DefaultMap(field);
    }
    if (field.options.get || field.options.set) {
      return new GetterSetterMap(field);
    }
    if (field.options.map) {
      return new FnMap(field);
    }
    if (field.options.ref) {
      return new ReferenceMap(field);
    }
    return new NoMap(field);
  };

}).call(this);
