// Generated by CoffeeScript 1.6.2
(function() {
  var FnMapper;

  FnMapper = (function() {
    /*
    */
    function FnMapper(field) {
      this.field = field;
    }

    /*
    */


    FnMapper.prototype.map = function(model, value) {
      return this.field.options.map.call(model, value);
    };

    /*
    */


    FnMapper.prototype.toObject = function(model, value) {
      return value;
    };

    return FnMapper;

  })();

  module.exports = FnMapper;

}).call(this);
