// Generated by CoffeeScript 1.6.2
(function() {
  var GetterSetterMap, type;

  type = require("type-component");

  GetterSetterMap = (function() {
    /*
    */
    function GetterSetterMap(field) {
      this.field = field;
      this._get = field.options.get || function(model, value) {
        return value;
      };
      this._set = field.options.set || function() {};
      this._bind = field.options.bind || [];
    }

    /*
    */


    GetterSetterMap.prototype.map = function(model, value) {
      var _get, _set;

      _set = function(value) {};
      _get = function() {};
      if (this._bind.length) {
        model.bind(this._bind.join(",")).to(_get);
      }
      return _get();
    };

    return GetterSetterMap;

  })();

  module.exports = GetterSetterMap;

}).call(this);
