// Generated by CoffeeScript 1.6.2
(function() {
  var GetterSetterMap, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  GetterSetterMap = (function(_super) {
    __extends(GetterSetterMap, _super);

    /*
    */


    function GetterSetterMap(field) {
      GetterSetterMap.__super__.constructor.call(this, field);
      this._get = field.options.get || function(model, value) {
        return value;
      };
      this._set = field.options.set || function() {};
      this._bind = field.options.bind || [];
    }

    /*
    */


    GetterSetterMap.prototype.map = function(model, value) {
      var _get, _set;

      _set = function(value) {};
      _get = function() {};
      if (this._bind.length) {
        model.bind(this._bind.join(",")).to(_get);
      }
      return _get();
    };

    return GetterSetterMap;

  })(require("./base"));

  module.exports = GetterSetterMap;

}).call(this);
