// Generated by CoffeeScript 1.6.2
(function() {
  var NoMapper;

  NoMapper = (function() {
    /*
    */
    function NoMapper() {}

    /*
    */


    NoMapper.prototype.map = function(model, data) {
      return data;
    };

    /*
    */


    NoMapper.prototype.toObject = function(model, data) {
      return data;
    };

    return NoMapper;

  })();

  module.exports = NoMapper;

}).call(this);
