// Generated by CoffeeScript 1.6.2
(function() {
  var ReferenceMap, type;

  type = require("type-component");

  ReferenceMap = (function() {
    /*
    */
    function ReferenceMap(field) {
      this.field = field;
      this._ref = this.field.options.ref;
    }

    /*
    */


    ReferenceMap.prototype.map = function(model, value) {
      var refModel;

      if (value == null) {
        return;
      }
      if (value != null ? value.__isModel : void 0) {
        if (value.schema.name !== this._ref) {
          throw new Error("cannot set model type \"" + value.schema.name + "\" on \"" + this._ref + "\"");
        }
        return value;
      }
      refModel = this.field.linen.model(this._ref, value);
      return refModel;
    };

    return ReferenceMap;

  })();

  module.exports = ReferenceMap;

}).call(this);
