// Generated by CoffeeScript 1.6.2
(function() {
  var ReferenceMap, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  ReferenceMap = (function(_super) {
    __extends(ReferenceMap, _super);

    /*
    */


    function ReferenceMap(field) {
      ReferenceMap.__super__.constructor.call(this, field);
      this._ref = field.options.ref;
    }

    /*
    */


    ReferenceMap.prototype.map = function(model, value) {
      var refModel;

      if (value == null) {
        return ReferenceMap.__super__.map.call(this, model, value);
      }
      if (value != null ? value.__isModel : void 0) {
        if (value.schema.name !== this._ref) {
          throw new Error("cannot set model type \"" + value.schema.name + "\" on \"" + this._ref + "\"");
        }
        return value;
      }
      refModel = this.field.linen.model(this._ref, value);
      refModel.owner = model;
      return refModel;
    };

    return ReferenceMap;

  })(require("./base"));

  module.exports = ReferenceMap;

}).call(this);
